version: '3.8'

services:
  m3u8-player:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: m3u8-player
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      # 如果需要其他环境变量，可以在这里添加
      # - CUSTOM_VAR=value
    volumes:
      # 可选：挂载配置文件
      # - ./config:/app/config:ro
      # 可选：挂载日志目录
      # - ./logs:/app/logs
    networks:
      - m3u8-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 可选：添加 Nginx 反向代理
  # nginx:
  #   image: nginx:alpine
  #   container_name: m3u8-nginx
  #   restart: unless-stopped
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./nginx/ssl:/etc/nginx/ssl:ro
  #   depends_on:
  #     - m3u8-player
  #   networks:
  #     - m3u8-network

networks:
  m3u8-network:
    driver: bridge
